create directory for personal theme

diff --git a/bin/fvwm-themes-start.in b/bin/fvwm-themes-start.in
--- a/bin/fvwm-themes-start.in
+++ b/bin/fvwm-themes-start.in
@@ -66,7 +66,8 @@ destRcFile2="$themesName/$realCurrentThemeName/$rcName2"
 # POSIX says that we can have symlink to a not existing file.
 # However some 2.3.x Linux kernels and may be 2.4.x do not support this???
 [ -d $themesDir ] || mkdir $themesDir
-cd $themesDir
+[ -d $themesDir/personal ] || mkdir $themesDir/personal
+cd $themesDir || echo "Fatal error, can't chdir $themesDir"
 if [ ! -d $realCurrentThemeName ]; then
 	mkdir $realCurrentThemeName
 	isNewSession=1
